name: flutter_application_1
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.46.0
  toggle_switch: ^1.4.0
  font_awesome_flutter: ^9.2.0
  sleek_circular_slider: ^2.0.1
  settings_ui: ^2.0.2
  http: ^0.13.4
  circular_menu: ^1.2.3
  day_night_time_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
